name: vesper_cuda
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - cudatoolkit=11.8
  - pip
  - pytorch
  - mrcfile
  - numba
  - numpy
  - pyFFTW
  - scipy
  - tqdm
  - biopython
  - scikit-learn
